name: Java CI 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: actions/cache@v1
      name: Setup local Maven repository (cache)
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-maven-
      
    - uses: actions/setup-java@v1
      name: Setup Java JDK 11 (x64)
      with:
        java-version: 11
        architecture: x64
    
    - name: Build with Maven
      run: mvn clean package
